config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", confirmations: "confirmations" }
  resources :users, except: [:new] do
    get :connections, on: :member
    get :connect, on: :member
    get :accept_connection, on: :member
    get :remove_connection, on: :member
    get :decline_connection, on: :member
    post :message, on: :member
  end
  resources :connections, only: [:index]
  resources :conversations
  resources :messages
  resources :endorsements
  resources :products, only:[:index, :show]
  resources :charges, only: [:create] do 
    post :check_coupon, on: :collection
  end
  resources :posts, path: 'feed' do
    post :like, on: :member
    post :unlike, on: :member
  end
  resources :post_comments
  match "/invitation_codes/check" => "invitation_codes#check", via: [:post]
  get "/invitation_codes/check", to: redirect('/')
  

  resources :categories, only: [:index, :show]
  resources :job_applications
  resources :jobs do
    get :apply, on: :member
    get :my, on: :collection
  end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match "/:slug" => "pages#show", via: [:get], as: 'show_page'
  root 'posts#index'
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  after_create :set_last_message_at
  default_scope { order('created_at DESC') }
  self.per_page = 20

  attr_accessor :recipient_id

  def message_time
   created_at.strftime("%m/%d/%y at %l:%M %p")
  end

  def set_last_message_at
    self.conversation.last_message_at = Time.now
    self.conversation.save
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages/new
  def new
    @message = Message.new
  end

  # POST /messages
  # POST /messages.json
  def create
    @recipient = User.find(params[:message][:recipient_id])
    @conversation = Conversation.between(current_user,@recipient).first_or_create(sender_id: current_user.id, recipient_id: @recipient.id)
    @message = @conversation.messages.build(user: current_user, body: params[:message][:body])
    authorize @message

    respond_to do |format|
      if @message.save
        format.html { redirect_to @conversation, notice: 'Message sent.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
      authorize @message
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.fetch(:message, {}).permit(:body)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for Message.new do |f| %>
  <%= f.error_notification %>
  <%= f.input :recipient_id, as: :hidden, input_html: { value: recipient_id } %>
  <%= f.input :body, label: false %>
  <%= f.button :submit, value: "Send", class: 'float-right' %>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>