config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", confirmations: "confirmations" }
  resources :users, except: [:new] do
    get :connections, on: :member
    get :connect, on: :member
    get :accept_connection, on: :member
    get :remove_connection, on: :member
    get :decline_connection, on: :member
    post :message, on: :member
  end
  resources :connections, only: [:index]
  resources :conversations
  resources :messages
  resources :endorsements
  resources :products, only:[:index, :show]
  resources :charges, only: [:create] do 
    post :check_coupon, on: :collection
  end
  resources :posts, path: 'feed' do
    post :like, on: :member
    post :unlike, on: :member
  end
  resources :post_comments
  match "/invitation_codes/check" => "invitation_codes#check", via: [:post]
  get "/invitation_codes/check", to: redirect('/')
  

  resources :categories, only: [:index, :show]
  resources :job_applications
  resources :jobs do
    get :apply, on: :member
    get :my, on: :collection
  end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match "/:slug" => "pages#show", via: [:get], as: 'show_page'
  root 'posts#index'
  
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :poster, class_name: 'User'
  belongs_to :category
  has_many :applications, class_name: 'JobApplication', dependent: :destroy
  has_many :applicants, through: :applications
  validates_presence_of :job_type, :title, :description, :category, :poster
  validate :valid_credits
  after_create :reduce_credits

  enum job_type: {
    fulltime: 0,
    freelance: 1,
	}
  
  def valid_credits
    if self.job_type == 'fulltime' && self.poster.fulltime_postings_remaining < 1
      errors.add(:base,"You don't have enough full-time posting credits to post a new job.  Please purchase more to create a job.")
    end
    if self.job_type == 'freelance' && self.poster.freelance_postings_remaining < 1
      errors.add(:base,"You don't have enough freelance posting credits to post a new job.  Please purchase more to create a job.")
    end
  end

  def has_applied?(user)
    applications = self.applications.where(applicant_id: user.id)
    return applications.count > 0
  end

  def reduce_credits
    self.poster.fulltime_postings_remaining -= 1 if self.job_type == 'fulltime'
    self.poster.freelance_postings_remaining -= 1 if self.job_type == 'freelance'
    self.poster.save
  end

  # Scopes
  include Filterable
  scope :title, -> (title) { where('lower(title) like lower(?)', "#{title}%") }
  scope :category, -> (category) { where category: category }
  scope :job_type, -> (job_type) { where job_type: job_type }
  scope :country, -> (country) { where country: country }
  default_scope { order('created_at DESC') }
  self.per_page = 20

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, except: [:index, :new, :my, :create]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = policy_scope(Job).filter(filtering_params(params)).paginate(:page => params[:page])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    authorize @job
  end

  # GET /jobs/1/edit
  def edit
  end

  def my
    authorize Job
    @jobs = current_user.jobs.paginate(:page => params[:page])
  end

  # GET /jobs/1/apply
  def apply
    @application = @job.applications.create(applicant: current_user)
    if @application.errors.any?
      flash[:error] = @application.errors.full_messages.join('<br>')
    else
      flash[:success] = 'Applied for job.'
    end
    redirect_to :back
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.poster = current_user
    authorize @job
    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      flash[:error] = @job.errors.full_messages.join('<br>')
      render :new
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
      authorize @job
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_type, :title, :country, :description, :category_id)
    end

    # A list of the param names that can be used for filtering
    def filtering_params(params)
      params.slice(:title, :category, :country, :job_type)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>

  <div class="form-inputs">
    <%= f.input :job_type %>
    <%= f.input :title %>
    <%= f.input :country, collection: ISO3166::Country.translations %>
    <%= f.association :category %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jobs/_list.html.erb
<div class="jobs">
  <% jobs.each do |job| %>
    <div class="job">
      <a href="<%= job_path(job) %>">
        <div class="job-info">
          <div class="avatar-wrapper">
            <%= job.poster.render_avatar %>
          </div>
          <div class="media-body">
            <div class="job-title h3"><%= job.title %><div class="badge badge-job"><%= job.job_type.capitalize %></div></div>
            <div class="job-category h6"><%= job.category.name %></div>
            <div class="job-description"><%= truncate(job.description, length: 80) %></div>
          </div>
        </div>
        <div class="job-meta">
          <div class="row">
            <div class="col-6">
              <div class="job-created-date"><i class="ion-android-time"></i> <%= job.created_at.strftime('%b %d, %Y') %></div>      
            </div>
            <div class="col-6 text-right">
              <div class="applicant-count">Applicants: <%= job.applicants.count %></div>        
            </div>
          </div>
        </div>
      </a>
    </div>
  <% end %>
</div>

<%= will_paginate jobs %>

app/views/jobs/edit.html.erb
<% content_for :page_header do %>
    <h1>Editing Job</h1>
<% end %>
<div class="container">
    <div class="job-card mb-5">
        <div class="job-description">
            <%= render 'form', job: @job %>
        </div>
    </div>
</div>

app/views/jobs/index.html.erb
<% title 'Jobs' %>
<% meta_description "Search and filter available jobs for creative talent users." %>

<div class="page-header">
  <div class="container">
    <h1>Jobs</h1>
  </div>
</div>
<div class="container">

  <div class="row">
    <div class="col-md-3">
      <a class="btn btn-white d-md-none mb-4 d-block" data-toggle="collapse" href="#filters" aria-expanded="false" aria-controls="filters">
        <i class="ion-android-funnel"></i> Filters
      </a>
      <div class="filters collapse" id="filters">
        <%= simple_form_for(Job.new) do |f| %>
          <%= f.input :title, input_html: { name: :title, value: params[:title] } %>
          <%= f.input :category, collection: Category.all, selected: params[:category], input_html: { name: :category }, include_blank: 'Any' %>
          <%= f.input :job_type, selected: params[:job_type], input_html: { name: :job_type }, include_blank: 'Any' %>
          <%= f.input :country, collection: ISO3166::Country.translations.sort.map {|k,v| [v,k]}, selected: params[:country], input_html: { name: :country }, include_blank: 'Anywhere' %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 ml-auto">
      <%= render 'list', jobs: @jobs %>
    </div>
  </div>
</div>

app/views/jobs/my.html.erb
<% title 'My Job Postings' %>

<div class="page-header">
  <div class="container">
    <h1>My Job Postings <a href="<%= current_user.postings_remaining? ? new_job_path : products_path %>" class="btn btn-primary float-right">New Job</a></h1>
  </div>
</div>
<div class="container">

  <div class="alert alert-<%= current_user.postings_remaining? ? 'success' : 'warning' %> if " role="alert">
    You have <strong><%= current_user.fulltime_postings_remaining %></strong> full-time job posting credits remaining and <strong><%= current_user.freelance_postings_remaining %></strong> freelance job postings remaining.<br/>
    <%= link_to products_path do %>Purchase more now<% end %>
  </div>
  <div class="row">
    <div class="col-md-12">
        <%= render 'list', jobs: @jobs %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<%= content_for :page_header do %>
    <h1>New Job</h1>
<% end %>

<div class="container">

    <div class="job-card mb-5">
        <div class="job-description">
            <%= render 'form', job: @job %>
        </div>
    </div>

</div>

app/views/jobs/show.html.erb
<% title @job.title %>
<% meta_description @job.description.truncate(150) %>

<div class="container">
  <% content_for :page_header do %>
    <h1><%= @job.title %></h1>
    <h3><%= @job.category.name %></h3>
  <% end %>

  <div class="job-card mb-5">
    <div class="job-description">
      <%= simple_format(@job.description) %>
    </div>
    <% if policy(@job).update? %>
      <%= link_to '<i class="ion-edit"></i> Edit'.html_safe, edit_job_path(@job), class: 'mt-4 d-block' %>
    <% end %>
  </div>

  <div class="job-apply">
    <% if @job.errors.any? %>
      <% @simulation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>
    <% if policy(@job).apply? %>    
      <%= link_to 'Apply', apply_job_path(@job), class: 'btn btn-primary' %>
    <% end %>
  </div>

  <% if policy(@job).edit? %>    
    <h3>Applicants</h3>
    <div class="applicants">
      <% @job.applicants.each do |applicant| %>
        <div class="applicant">
          <a href="<%= user_path(applicant) %>">
            <%= applicant.render_avatar %>
            <%= applicant.name %>
          </a>
        </div>
      <% end %>
    </div>
  <% end %>

</div>