config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", confirmations: "confirmations" }
  resources :users, except: [:new] do
    get :connections, on: :member
    get :connect, on: :member
    get :accept_connection, on: :member
    get :remove_connection, on: :member
    get :decline_connection, on: :member
    post :message, on: :member
  end
  resources :connections, only: [:index]
  resources :conversations
  resources :messages
  resources :endorsements
  resources :products, only:[:index, :show]
  resources :charges, only: [:create] do 
    post :check_coupon, on: :collection
  end
  resources :posts, path: 'feed' do
    post :like, on: :member
    post :unlike, on: :member
  end
  resources :post_comments
  match "/invitation_codes/check" => "invitation_codes#check", via: [:post]
  get "/invitation_codes/check", to: redirect('/')
  

  resources :categories, only: [:index, :show]
  resources :job_applications
  resources :jobs do
    get :apply, on: :member
    get :my, on: :collection
  end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match "/:slug" => "pages#show", via: [:get], as: 'show_page'
  root 'posts#index'
  
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order('position ASC') }
  has_many :jobs
  has_many :users
  has_attached_file :image
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  validates :name, presence: true, uniqueness: true
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    skip_policy_scope
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :position)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/_list.html.erb
<div class="categories row">
  <% Category.all.each do |category| %>
    <div class="col-md-3">
      <a href="<%= jobs_path(category: category.id) %>">
        <div class="category">
            <%= image_tag (category.image_file_name ? category.image : 'categories/' + category.name.parameterize + '.png')  %>
            <h3 class="category-name"><%= category.name %></h3>
        </div>
      </a>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% body_class 'header-dark-active home' %>
<% title 'Professional Network' %>
<% meta_description "World's first dedicated Social networks for creative professional talent." %>


<div class="hero inverse-bg">
  <div class="container text-center">
    <h1>What's your gig?</h1>
    <p class="h4 mb-5">A global professional network to discover and connect creative talents.</p>
  </div>
</div>

<div class="container section-padded text-center">
  <h2>Find the perfect talent for your gig</h2>
  <%= render 'list' %>
  <%= link_to 'Explore More', users_path, class: 'btn btn-lg btn-primary mt-5' %>  
</div>

<div class="section-padded text-center" style="background:#ffffff;">
  <div class="container">
    <h2>Why Gigz?</h2>
    <div class="row">
      <div class="col-md-3 feature">
        <%= image_tag 'create.png' %>
        <h3>Create</h3>
        <p>Instantly set up your social profile free of charge.</p>
      </div>
      <div class="col-md-3 feature">
        <%= image_tag 'discover.png' %>
        <h3>Discover</h3>
        <p>Start adding talent to your network and immerse yourself with the incredible innovations in the works.</p>
      </div>
      <div class="col-md-3 feature">
        <%= image_tag 'post.png' %>
        <h3>Post</h3>
        <p>Add permanent or freelance gigs to the job board and start hiring creative talent to complete your endeavors.</p>
      </div>
      <div class="col-md-3 feature">
        <%= image_tag 'hire.png' %>
        <h3>Hire</h3>
        <p>Browse profiles and resumes of applicants to interview and hire top candidates to begin your gig.</p>
      </div>
    </div>
  </div>
</div>

<div class="section-padded section-subscribe inverse-bg text-center">
  <div class="container">
    <h2>Subscribe for free leads from Gigz!</h2>
    <div id="mc_embed_signup">
        <form action="//ourgigz.us16.list-manage.com/subscribe/post?u=1c5d46e9486891914ec55e0c8&amp;id=8db999d57d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
          <div id="mc_embed_signup_scroll">
          <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email address" required="">
          <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
          <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_1c5d46e9486891914ec55e0c8_8db999d57d" tabindex="-1" value=""></div>
          <button type="submit" class="btn-submit"><i class="ion-paper-airplane"></i></button>
          </div>
        </form>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>