config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", confirmations: "confirmations" }
  resources :users, except: [:new] do
    get :connections, on: :member
    get :connect, on: :member
    get :accept_connection, on: :member
    get :remove_connection, on: :member
    get :decline_connection, on: :member
    post :message, on: :member
  end
  resources :connections, only: [:index]
  resources :conversations
  resources :messages
  resources :endorsements
  resources :products, only:[:index, :show]
  resources :charges, only: [:create] do 
    post :check_coupon, on: :collection
  end
  resources :posts, path: 'feed' do
    post :like, on: :member
    post :unlike, on: :member
  end
  resources :post_comments
  match "/invitation_codes/check" => "invitation_codes#check", via: [:post]
  get "/invitation_codes/check", to: redirect('/')
  

  resources :categories, only: [:index, :show]
  resources :job_applications
  resources :jobs do
    get :apply, on: :member
    get :my, on: :collection
  end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match "/:slug" => "pages#show", via: [:get], as: 'show_page'
  root 'posts#index'
  
end

app/models/charge.rb
class Charge < ApplicationRecord

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def check_coupon
    authorize Charge
    @coupon = Coupon.find_by_code(params[:couponCode])
    render json: @coupon
  end

  def create
    authorize Charge    
    # Amount in cents
    @product = Product.find(params[:productId])
    @quantity = params[:quantity].to_i
    @amount = @quantity * @product.price
    @final_amount = @amount
  
    @code = params[:couponCode]
  
    if !@code.blank?
      @coupon = Coupon.find_by_code(params[:couponCode])    
  
      if @coupon.nil?
        flash[:error] = 'Coupon code is not valid or expired.'
        redirect_to new_charge_path
        return
      else
        @final_amount = @coupon.get_discount(@amount).to_i
      end
  
      charge_metadata = {
        :coupon_code => @code,
        :coupon_value_discount => (@coupon.value_discount).to_s,
        :coupon_percentage_discount => (@coupon.percentage_discount).to_s + "%"
      }
    end
  
    charge_metadata ||= {}
  
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
    @charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @final_amount,
      :description => 'Gigz Stripe customer',
      :currency    => 'usd',
      :metadata    => charge_metadata
    )

    
    if @charge.status == 'succeeded'
      @sale = Sale.create(
        stripe_customer_id: customer.id,
        customer_id: current_user.id,
        product_id: @product.id,
        amount: @final_amount,
        quantity: @quantity,
        currency: 'usd',
      )
      @sale.coupon_id = @coupon.id if !@coupon.nil?
      @sale.save
      current_user.freelance_postings_remaining += @quantity if @product.job_type == 'freelance'
      current_user.full_time_postings_remaining += @quantity if @product.job_type == 'full_time'
      current_user.save
      flash[:success] = 'Order was successful.'
    end
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class="container content-container">
    <div class="row">
        <div class="col-md-5 mx-auto">
            <div class="box">
                <h2>Order Summary</h2>
                <label class="product">
                    <span>Product: <%= @product.name %></span>
                </label>
                <label class="quantity">
                    <span>Quantity: <%= @quantity %></span>
                </label>
                <label class="subtotal">
                    <span>Subtotal: <%= number_to_currency(@amount * 0.01) %></span>
                </label>
                <% if !@coupon.nil? %>
                    <p>
                        <label class="coupon">
                        <span>Coupon: <%= @coupon.code %></span>
                        </label>
                    </p>
                <% end %>
                <div class="total mb-4">
                    <span style="font-weight:bold">Total: <%= number_to_currency(@final_amount * 0.01) %></span>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <%= link_to 'Create Job', new_job_path, class: 'btn btn-primary d-block' %>                    
                    </div>
                    <div class="col-md-6">
                        <%= link_to 'My Jobs', my_jobs_path, class: 'btn btn-secondary d-block' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <p>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </p>
  <p>
    <%= label_tag(:couponCode, 'Coupon:') %>
    <%= text_field_tag(:couponCode) %>
  </p>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Your Purchase"
          data-locale="auto"></script>
<% end %>